services:
  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://backend:3000
    ports:
      - "5000:80"
    networks:
      - ploybout-network
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - ploybout-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: verbal-effect
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ploybout-network

networks:
  ploybout-network:
    driver: bridge

volumes:
  postgres-data:
